# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/forecast',
                'doc_host': 'https://maimanuel.github.io',
                'git_url': 'https://github.com/maimanuel/forecast',
                'lib_path': 'forecast'},
  'syms': {'forecast.core': {'forecast.core.fool_print': ('core.html#fool_print', 'forecast/core.py')}}}